SELECT UGB.TITLE AS TITLE, UGB.BOARD_ID AS BOARD_ID, UGR.REPLY_ID AS REPLY_ID,
       UGR.WRITER_ID AS WRITER_ID, UGR.CONTENTS AS CONTENTS,
       DATE_FORMAT(UGR.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD AS UGB, USED_GOODS_REPLY AS UGR
WHERE DATE_FORMAT(UGB.CREATED_DATE, "%Y-%m-%d") LIKE "2022-10%"
  AND UGB.BOARD_ID = UGR.BOARD_ID
ORDER BY CREATED_DATE ASC, TITLE ASC;