SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME,
       SUM(FO.AMOUNT * FP.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP, FOOD_ORDER AS FO
WHERE DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m-%d') LIKE "2022-05%"
  AND FP.PRODUCT_ID = FO.PRODUCT_ID
GROUP BY FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC;