SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT,
       DATE_FORMAT(RR.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE AS MP, REST_REVIEW AS RR
WHERE RR.MEMBER_ID = (SELECT MEMBER_ID
                      FROM REST_REVIEW
                      GROUP BY MEMBER_ID
                      ORDER BY COUNT(*) DESC
                      LIMIT 1)
  AND MP.MEMBER_ID = RR.MEMBER_ID
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC;