SELECT COUNT(DISTINCT NAME) AS COUNT
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
;

/*
 SELECT COUNT(*) AS COUNT
 FROM ANIMAL_INS
 -- WHERE NAME IS NOT NULL
 GROUP BY NAME
    -- HAVING NAME IS NOT NULL
 */
 -- GROUP BY로 하면 이름마다 몇 개가 존재하는지가 세어진다
 -- ORACLE에서는 이렇게 쓴다고 하지만 MYSQL에서는 아니다